### PR TITLE
improving the donation modal & projects loading

### PR DESCRIPTION
**Pull request by M-Rb3**
- move the success donation modal for the web wallet to the root.
- make all the fetching done on the pot page to use bos storage

### CODE REVIEW

**Review by wpdas — COMMENTED** [review]
Fix the broken test before merging, please.

**Review by wpdas — CHANGES_REQUESTED** [review]
need to work on home page

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Initially says "0 projects", then says "Loading...", then first load/render of project cards displays essentially blank cards before finally the populated cards are displayed. Would be better to display skeleton cards until the data has loaded, and remove the "Loading..." text.

See video:

https://github.com/PotLock/bos-app-alem/assets/54282009/c4c23ea9-629d-4b5b-b43f-839792e390bb

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Still taking a super long time for the projects to load (see screen recording). Is that because we wait to calculate the estimated matched amount for each project card?

Two options:

1. Refactor so that the estimated matched amounts calculate within the context of the card and not the ListPage component, but this might be tricky / not worth the time

2. Quick and dirty: remove Estimated Matched Amount from project card, since we have it in "Payouts" now anyway, plus the leaderboard. Just comment out, don't completely delete it, in case we change our minds.

I vote for #2

https://github.com/PotLock/bos-app-alem/assets/54282009/ef989cef-0369-4351-92b8-b23664749e37

**Comment by lachlanglen** [comment]
Oh also - please remove the 'Loading...' text in the UI while projects are loading. it should go straight to skeletons.

**Comment by M-Rb3** [comment]
@lachlanglen 
the loading is coming from mob. near InfinteScroll component,  😂 I took a look at it, but I have no idea what is going up there, building a new one is easier, I worked with Wonderson on making the card stateless component, which should make it a lot faster now. notify me if you still getting the "loading" text

https://github.com/PotLock/bos-app-alem/assets/68287884/337279d9-b550-4ba8-af6b-5827938b95b9

**Review by lachlanglen — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
